include_1d:
  mask: false
  origin: false
  einstein_radius: true
  half_light_radius: true
include_2d:
  mask: true
  origin: false
  border: false
  grid: false
  positions: true
  tangential_critical_curves: true
  tangential_caustics: true
  radial_critical_curves: true
  radial_caustics: true
  light_profile_centres: true
  mass_profile_centres: true
  multiple_images: true
  mapper_image_plane_mesh_grid: false
  mapper_source_plane_data_grid: false
  mapper_source_plane_mesh_grid: false
