#!/bin/bash -l

#SBATCH --ntasks 1
#SBATCH -J example
#SBATCH --array=1-8
#SBATCH -o ../output.%A.%a.out
#SBATCH -e ../error.%A.%a.err
#SBATCH -p cordelia
#SBATCH -A durham
#SBATCH -t 6:00:00   # longest job
#SBATCH --mem=30G
#SBATCH --mail-type=END                          # notifications for job done & fail
#SBATCH --mail-user=your_name@durham.ac.uk

module purge
module load python/3.6.5
source /cosma/home/durham/pdtw24/PyAutoLens/bin/activate_jam

python3 $WORKSPACE/runners/example.py $SLURM_ARRAY_TASK_ID
