ExponentialCore:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  intensity:
    type: LogUniform
    lower_limit: 1.0e-05
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
  alpha:
    type: Constant
    value: 3.0      
  gamma:
    type: Constant
    value: 0.25
  radius_break:
    type: Constant
    value: 0.025
ExponentialCoreSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-05
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
  alpha:
    type: Constant
    value: 3.0      
  gamma:
    type: Constant
    value: 0.25      
  radius_break:
    type: Constant
    value: 0.025
