#!/bin/bash -l

#SBATCH -N 1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH -J example
#SBATCH -o ../output.%A.%a.out
#SBATCH -e ../error.%A.%a.err
#SBATCH -p cosma
#SBATCH -A durham
#SBATCH -t 48:00:00   # longest job
#SBATCH --mail-type=END                      # notifications for job done & fail
#SBATCH --mail-user=your_name@durham.ac.uk

module purge
module load python/3.6.5
source /cosma/home/durham/pdtw24/PyAutoLens/bin/activate_jam
export OPENBLAS_NUM_THREADS=4
export MKL_NUM_THREADS=4

srun -n 16 --multi-prog example_muticonf.conf
