#!/bin/bash -l

#SBATCH -N 1
#SBATCH --ntasks=14
#SBATCH -J example
#SBATCH -o ../output/output.%A.%a.out
#SBATCH -e ../error/error.%A.%a.err
#SBATCH -p cosma
#SBATCH -A durham
#SBATCH -t 48:00:00   # longest job
#SBATCH --mail-type=END                      # notifications for job done & fail
#SBATCH --mail-user=james.w.nightingale@durham.ac.uk

module purge
module load python/3.6.5
source /cosma/home/durham/pdtw24/PyAutoLens/bin/activate

srun -n 14 --multi-prog example_muticonf.conf
