#!/bin/bash -l

#SBATCH -N 1
#SBATCH --ntasks=14
#SBATCH -J example
#SBATCH -o output/output.%A.%a.out
#SBATCH -e error/error.%A.%a.err
#SBATCH -p cosma
#SBATCH -A durham
#SBATCH -t 48:00:00   # longest job
#SBATCH --mail-type=END                      # notifications for job done & fail
#SBATCH --mail-user=james.w.nightingale@durham.ac.uk

module purge
module load python/3.6.5
cp -r /cosma/home/durham/pdtw24/PyAutoLens /cosma5/data/autolens/venvs/PyAutoLens.$SLURM_JOB_ID
rm -rf /cosma5/data/autolens/venvs/PyAutoLens.$SLURM_JOB_ID/workspace
rm -rf /cosma5/data/autolens/venvs/PyAutoLens.$SLURM_JOB_ID/workspace_jam
source /cosma5/data/autolens/venvs/PyAutoLens.$SLURM_JOB_ID/bin/activate

srun -n 14 --multi-prog example_muticonf.conf
