#!/bin/bash -l

#SBATCH -N 1
#SBATCH --ntasks=14
#SBATCH --cpus-per-task=1
#SBATCH -J example
#SBATCH -o ../output.%A.%a.out
#SBATCH -e ../error.%A.%a.err
#SBATCH -p cosma6
#SBATCH -A dp004
#SBATCH -t 48:00:00   # longest job
#SBATCH --mail-type=END                      # notifications for job done & fail
#SBATCH --mail-user=james.w.nightingale@durham.ac.uk

module purge
module load python/3.6.5
source /cosma/home/durham/pdtw24/PyAutoLens/bin/activate_jam

srun -n 16 --multi-prog example_muticonf.conf
