# Certain light and mass profile calculations become ill defined at (0.0, 0.0) or close to this value. This can lead
# to numerical issues in the calculation of the profile, for example a np.nan may arise, crashing the code. 
  
# To avoid this, we set a minimum value for the radial coordinate of the profile. If the radial coordinate is below 
# this value, it is rounded up to this value. This ensures that the profile cannot receive a radial coordinate of 0.0.

# For example, if an input grid coordinate has a radial coordinate of 1e-12, for most profiles this will be rounded up
# to radial_minimum=1e-08. This is a small enough value that it should not impact the results of the profile calculation.

radial_minimum:
  radial_minimum:
    Chameleon: 1.0e-08
    ChameleonSph: 1.0e-08
    DevVaucouleurs: 1.0e-06
    DevVaucouleursSph: 1.0e-06
    dPIE: 1.0e-08
    dPIESph: 1.0e-08
    ExponentialGradient: 1.0e-06
    ExponentialGradientSph: 1.0e-06
    ElsonFreeFall: 1.0e-08
    ElsonFreeFallSph: 1.0e-08
    Exponential: 1.0e-06
    ExponentialCore: 1.0e-06
    ExponentialCoreSph: 1.0e-06
    ExponentialSph: 1.0e-06
    ExternalShear: 1.0e-08
    Gaussian: 1.0e-08
    GaussianGradient: 1.0e-08
    GaussianSph: 1.0e-08
    gNFW: 1.0e-06
    gNFWMCRLudlow: 1.0e-06
    gNFWSph: 1.0e-06
    Isothermal: 1.0e-08
    IsothermalCore: 1.0e-08
    IsothermalCoreSph: 1.0e-08
    IsothermalSph: 1.0e-08
    MassSheet: 1.0e-08
    Moffat: 1.0e-08
    MoffatSph: 1.0e-08
    PowerLawMultipole: 1.0e-08
    NFW: 1.0e-06
    NFWMCRDuffySph: 1.0e-06
    NFWMCRLudlow: 1.0e-06
    NFWMCRLudlowSph: 1.0e-06
    NFWMCRScatterLudlow: 1.0e-06
    NFWMCRScatterLudlowSph: 1.0e-06
    NFWSph: 1.0e-06
    NFWTruncatedMCRDuffySph: 1.0e-06
    NFWTruncatedMCRLudlowSph: 1.0e-06
    NFWTruncatedMCRScatterLudlowSph: 1.0e-06
    NFWTruncatedSph: 1.0e-06
    PointMass: 1.0e-08
    PowerLaw: 1.0e-08
    PowerLawBroken: 1.0e-08
    PowerLawBrokenSph: 1.0e-08
    PowerLawCore: 1.0e-08
    PowerLawCoreSph: 1.0e-08
    PowerLawSph: 1.0e-08
    Sersic: 1.0e-06
    SersicCore: 1.0e-06
    SersicCoreSph: 1.0e-06
    SersicGradient: 1.0e-06
    SersicSph: 1.0e-06
    SersicGradientSph: 1.0e-06
    ShapeletCartesianSph: 1.0e-8
    ShapeletCartesian: 1.0e-8
    ShapeletPolarSph: 1.0e-8
    ShapeletPolar: 1.0e-8
    ShapeletExponentialSph: 1.0e-8
    ShapeletExponential: 1.0e-8
    SMBH: 1.0e-8
    SMBHBinary: 1.0e-8



# Over sampling is an important numerical technique, whereby light profiles images are evaluated on a higher resolution
# grid than the image data to ensure the calculation is accurate.

# By default, a user does not specify the over sampling factor, and a default over sampling scheme is used for each
# profile. This scheme first goes to the centre of the profile, and computes circles with certain radial values
# (e.g. radii). It then assigns an over sampling `sub_size` to each circle, where the central circles have the highest
# over sampling factor and the outer circles have the lowest.

# The size of the circles that are appropriate for determining the over sampling factor are dependent on the resolution
# of the grid. For a high resolution grid (e.g. low pixel scale), a smaller circle central circle is necessary to
# over sample the profile accurately. The config file below therefore specifies the "radial factors" used for
# automatically determining the over sampling factors for each profile, which is the factor the pixel scale is multiplied
# by to determine the circle size.

# The config entry below defines the default over sampling factor for each profile, where:

# radial_factor_list: The factors that are multiplied by the pixel scale to determine the circle size that is used.
# sub_size_list: The over sampling factor that is used for each circle size.

# For the default entries below, oversampling of degree 32 x 32 is used within a circle of radius 3.01 x pixel scale,
# 4 x 4 within a circle of radius 10.01 x pixel scale and 2 x 2 for all pixels outside of this radius.

over_sampling:
  radial_factor_list:
    Chameleon: [3.01, 10.01]
    ChameleonSph: [3.01, 10.01]
    DevVaucouleurs: [3.01, 10.01]
    DevVaucouleursSph: [3.01, 10.01]
    dPIE: [3.01, 10.01]
    dPIESph: [3.01, 10.01]
    ExponentialGradient: [3.01, 10.01]
    ExponentialGradientSph: [3.01, 10.01]
    ElsonFreeFall: [3.01, 10.01]
    ElsonFreeFallSph: [3.01, 10.01]
    Exponential: [3.01, 10.01]
    ExponentialCore: [3.01, 10.01]
    ExponentialCoreSph: [3.01, 10.01]
    ExponentialSph: [3.01, 10.01]
    ExternalShear: [3.01, 10.01]
    Gaussian: [3.01, 10.01]
    GaussianSph: [3.01, 10.01]
    GaussianGradient: [3.01, 10.01]
    GaussianGradientSph: [3.01, 10.01]    
    gNFW: [3.01, 10.01]
    gNFWMCRLudlow: [3.01, 10.01]
    gNFWVirialMassConcSph: [3.01, 10.01]
    gNFWSph: [3.01, 10.01]
    Isothermal: [3.01, 10.01]
    IsothermalCore: [3.01, 10.01]
    IsothermalCoreSph: [3.01, 10.01]
    IsothermalSph: [3.01, 10.01]
    MassSheet: [3.01, 10.01]
    Moffat: [3.01, 10.01]
    MoffatSph: [3.01, 10.01]
    PowerLawMultipole: [3.01, 10.01]
    NFW: [3.01, 10.01]
    NFWMCRDuffySph: [3.01, 10.01]
    NFWMCRLudlow: [3.01, 10.01]
    NFWMCRLudlowSph: [3.01, 10.01]
    NFWMCRScatterLudlow: [3.01, 10.01]
    NFWMCRScatterLudlowSph: [3.01, 10.01]
    NFWVirialMassConcSph: [3.01, 10.01]
    NFWSph: [3.01, 10.01]
    NFWTruncatedMCRDuffySph: [3.01, 10.01]
    NFWTruncatedMCRLudlowSph: [3.01, 10.01]
    NFWTruncatedMCRScatterLudlowSph: [3.01, 10.01]
    NFWTruncatedSph: [3.01, 10.01]
    PointMass: [3.01, 10.01]
    PowerLaw: [3.01, 10.01]
    PowerLawBroken: [3.01, 10.01]
    PowerLawBrokenSph: [3.01, 10.01]
    PowerLawCore: [3.01, 10.01]
    PowerLawCoreSph: [3.01, 10.01]
    PowerLawSph: [3.01, 10.01]
    Sersic: [3.01, 10.01]
    SersicCore: [3.01, 10.01]
    SersicCoreSph: [3.01, 10.01]
    SersicGradient: [3.01, 10.01]
    SersicSph: [3.01, 10.01]
    SersicGradientSph: [3.01, 10.01]
    ShapeletCartesianSph: [3.01, 10.01]
    ShapeletCartesian: [3.01, 10.01]
    ShapeletPolarSph: [3.01, 10.01]
    ShapeletPolar: [3.01, 10.01]
    ShapeletExponentialSph: [3.01, 10.01]
    ShapeletExponential: [3.01, 10.01]
    SMBH: [3.01, 10.01]
    SMBHBinary: [3.01, 10.01]
    EllProfile: [3.01, 10.01]
  sub_size_list:
    Chameleon: [32, 4, 2]
    ChameleonSph: [32, 4, 2]
    DevVaucouleurs: [32, 4, 2]
    DevVaucouleursSph: [32, 4, 2]
    dPIE: [32, 4, 2]
    dPIESph: [32, 4, 2]
    ExponentialGradient: [32, 4, 2]
    ExponentialGradientSph: [32, 4, 2]
    ElsonFreeFall: [32, 4, 2]
    ElsonFreeFallSph: [32, 4, 2]
    Exponential: [32, 4, 2]
    ExponentialCore: [32, 4, 2]
    ExponentialCoreSph: [32, 4, 2]
    ExponentialSph: [32, 4, 2]
    ExternalShear: [32, 4, 2]
    Gaussian: [32, 4, 2]
    GaussianSph: [32, 4, 2]
    GaussianGradient: [32, 4, 2]
    GaussianGradientSph: [32, 4, 2]    
    gNFW: [32, 4, 2]
    gNFWMCRLudlow: [32, 4, 2]
    gNFWVirialMassConcSph: [32, 4, 2]
    gNFWSph: [32, 4, 2]
    Isothermal: [32, 4, 2]
    IsothermalCore: [32, 4, 2]
    IsothermalCoreSph: [32, 4, 2]
    IsothermalSph: [32, 4, 2]
    MassSheet: [32, 4, 2]
    Moffat: [32, 4, 2]
    MoffatSph: [32, 4, 2]
    PowerLawMultipole: [32, 4, 2]
    NFW: [32, 4, 2]
    NFWMCRDuffySph: [32, 4, 2]
    NFWMCRLudlow: [32, 4, 2]
    NFWMCRLudlowSph: [32, 4, 2]
    NFWMCRScatterLudlow: [32, 4, 2]
    NFWMCRScatterLudlowSph: [32, 4, 2]
    NFWVirialMassConcSph : [32, 4, 2]
    NFWSph: [32, 4, 2]
    NFWTruncatedMCRDuffySph: [32, 4, 2]
    NFWTruncatedMCRLudlowSph: [32, 4, 2]
    NFWTruncatedMCRScatterLudlowSph: [32, 4, 2]
    NFWTruncatedSph: [32, 4, 2]
    PointMass: [32, 4, 2]
    PowerLaw: [32, 4, 2]
    PowerLawBroken: [32, 4, 2]
    PowerLawBrokenSph: [32, 4, 2]
    PowerLawCore: [32, 4, 2]
    PowerLawCoreSph: [32, 4, 2]
    PowerLawSph: [32, 4, 2]
    Sersic: [32, 4, 2]
    SersicCore: [32, 4, 2]
    SersicCoreSph: [32, 4, 2]
    SersicGradient: [32, 4, 2]
    SersicSph: [32, 4, 2]
    SersicGradientSph: [32, 4, 2]
    ShapeletCartesianSph: [32, 4, 2]
    ShapeletCartesian: [32, 4, 2]
    ShapeletPolarSph: [32, 4, 2]
    ShapeletPolar: [32, 4, 2]
    ShapeletExponentialSph: [32, 4, 2]
    ShapeletExponential: [32, 4, 2]
    SMBH: [32, 4, 2]
    SMBHBinary: [32, 4, 2]
    EllProfile: [32, 4, 2]