version: 1
disable_existing_loggers: false
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    stream: ext://sys.stdout
    formatter: formatter
  file:
    class: logging.FileHandler
    level: INFO
    filename: root.log
    formatter: formatter
root:
  level: DEBUG
  handlers:
  - console
  - file
formatters:
  formatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
