analysis:
  preload_attempts: 250
fits:
  flip_for_ds9: true
grid:
  remove_projected_centre: false
inversion:
  check_reconstruction: true        # If True, the inversion's reconstruction is checked to ensure the solution of a meshs's mapper is not an invalid solution where the values are all the same.
  reconstruction_vmax_factor: 0.5   # Plots of an Inversion's reconstruction use the reconstructed data's bright value multiplied by this factor.
hpc:
  hpc_mode: true
  iterations_per_update: 5000
adapt:
  adapt_minimum_percent: 0.01
  adapt_noise_limit: 100000000.0
model:
  ignore_prior_limits: false
numba:
  use_numba: true
  cache: false
  nopython: true
  parallel: false
output:
  force_pickle_overwrite: false
  info_whitespace_length: 80
  log_level: INFO
  log_to_file: false
  log_file: output.log
  model_results_decimal_places: 3
  remove_files: false
  samples_to_csv: true
parallel:
  warn_environment_variables: true
pixelization:
  voronoi_nn_max_interpolation_neighbors: 300
run_times:
  parallel_profile: false
  should_profile: false
  repeats: 1
structures:
  native_binned_only: false           # If True, data structures are only stored in their native and binned format. This is used to reduce memory usage in autocti.
test:
  check_likelihood_function: true   # if True, when a search is resumed the likelihood of a previous sample is recalculated to ensure it is consistent with the previous run.
  check_preloads: false
  exception_override: false
  preloads_check_threshold: 1.0     # If the figure of merit of a fit with and without preloads is greater than this threshold, the check preload test fails and an exception raised for a model-fit. 
  disable_positions_lh_inversion_check: true
