# Certain light and mass profile calculations become ill defined at (0.0, 0.0) or close to this value. This can lead
# to numerical issues in the calculation of the profile, for example a np.nan may arise, crashing the code. 
  
# To avoid this, we set a minimum value for the radial coordinate of the profile. If the radial coordinate is below 
# this value, it is rounded up to this value. This ensures that the profile cannot receive a radial coordinate of 0.0.

# For example, if an input grid coordinate has a radial coordinate of 1e-12, for most profiles this will be rounded up
# to radial_minimum=1e-08. This is a small enough value that it should not impact the results of the profile calculation.

radial_minimum:
  radial_minimum:
    Chameleon: 1.0e-08
    ChameleonSph: 1.0e-08
    DevVaucouleurs: 1.0e-06
    DevVaucouleursSph: 1.0e-06
    dPIE: 1.0e-08
    dPIESph: 1.0e-08
    ExponentialGradient: 1.0e-06
    ExponentialGradientSph: 1.0e-06
    ElsonFreeFall: 1.0e-08
    ElsonFreeFallSph: 1.0e-08
    Exponential: 1.0e-06
    ExponentialCore: 1.0e-06
    ExponentialCoreSph: 1.0e-06
    ExponentialSph: 1.0e-06
    ExternalShear: 1.0e-08
    Gaussian: 1.0e-08
    GaussianGradient: 1.0e-08
    GaussianSph: 1.0e-08
    gNFW: 1.0e-06
    gNFWMCRLudlow: 1.0e-06
    gNFWSph: 1.0e-06
    Isothermal: 1.0e-08
    IsothermalCore: 1.0e-08
    IsothermalCoreSph: 1.0e-08
    IsothermalSph: 1.0e-08
    MassSheet: 1.0e-08
    Moffat: 1.0e-08
    MoffatSph: 1.0e-08
    PowerLawMultipole: 1.0e-08
    NFW: 1.0e-06
    NFWMCRDuffySph: 1.0e-06
    NFWMCRLudlow: 1.0e-06
    NFWMCRLudlowSph: 1.0e-06
    NFWMCRScatterLudlow: 1.0e-06
    NFWMCRScatterLudlowSph: 1.0e-06
    NFWSph: 1.0e-06
    NFWTruncatedMCRDuffySph: 1.0e-06
    NFWTruncatedMCRLudlowSph: 1.0e-06
    NFWTruncatedMCRScatterLudlowSph: 1.0e-06
    NFWTruncatedSph: 1.0e-06
    PointMass: 1.0e-08
    PowerLaw: 1.0e-08
    PowerLawBroken: 1.0e-08
    PowerLawBrokenSph: 1.0e-08
    PowerLawCore: 1.0e-08
    PowerLawCoreSph: 1.0e-08
    PowerLawSph: 1.0e-08
    Sersic: 1.0e-06
    SersicCore: 1.0e-06
    SersicCoreSph: 1.0e-06
    SersicGradient: 1.0e-06
    SersicSph: 1.0e-06
    SersicGradientSph: 1.0e-06
    ShapeletCartesianSph: 1.0e-8
    ShapeletCartesian: 1.0e-8
    ShapeletPolarSph: 1.0e-8
    ShapeletPolar: 1.0e-8
    ShapeletExponentialSph: 1.0e-8
    ShapeletExponential: 1.0e-8