# The `plots` section customizes every image that is output to hard-disk during a model-fit.

# For example, if `plots: fit: subplot_fit=True``, the ``fit_dataset.png`` subplot file will 
# be plotted every time visualization is performed.

dataset:                                   # Settings for plots of all datasets (e.g. ImagingPlotter, InterferometerPlotter).
  subplot_dataset: true                    # Plot subplot containing all dataset quantities (e.g. the data, noise-map, etc.)?
  data: false                              # Plot the individual data of every dataset?
  noise_map: false                         # Plot the individual noise-map of every dataset?
  signal_to_noise_map: false               # Plot the individual signal-to-noise-map of every dataset?
  over_sampling: false            # Plot the over-sampling sub-size, used to evaluate light profiles, of every dataset?
  over_sampling_non_uniform: false  # Plot the over-sampling sub-size, used to evaluate non uniform grids, of every dataset?
  over_sampling_pixelization: false  # Plot the over-sampling sub-size, used to evaluate pixelizations, of every dataset?
imaging:                                   # Settings for plots of imaging datasets (e.g. ImagingPlotter)
   psf: false
positions:                                 # Settings for plots with resampling image-positions on (e.g. the image).
  image_with_positions: true
fit:                                       # Settings for plots of all fits (e.g. FitImagingPlotter, FitInterferometerPlotter).
  subplot_fit: true                        # Plot subplot of all fit quantities for any dataset (e.g. the model data, residual-map, etc.)?
  subplot_fit_log10: true                  # Plot subplot of all fit quantities for any dataset using log10 color maps (e.g. the model data, residual-map, etc.)?
  all_at_end_png: true                     # Plot all individual plots listed below as .png (even if False)?
  all_at_end_fits: true                    # Plot all individual plots listed below as .fits (even if False)?
  all_at_end_pdf: false                    # Plot all individual plots listed below as publication-quality .pdf (even if False)?
  subplot_of_planes: false                 # Plot subplot of the model-image, subtracted image and other quantities of each plane?
  subplot_galaxies_images: false              # Plot subplot of the image of each plane in the model?
  data: false                              # Plot individual plots of the data?
  noise_map: false                         # Plot individual plots of the noise-map?
  signal_to_noise_map: false               # Plot individual plots of the signal-to-noise-map?
  model_data: false                        # Plot individual plots of the model-data?
  residual_map: false                      # Plot individual plots of the residual-map?
  normalized_residual_map: false           # Plot individual plots of the normalized-residual-map?
  chi_squared_map: false                   # Plot individual plots of the chi-squared-map?
  residual_flux_fraction: false            # Plot individual plots of the residual_flux_fraction?
  model_images_of_planes: false            # Plot individual plots of each plane's model image?
  subtracted_images_of_planes: false       # Plot individual plots of each plane's subtracted image?
  plane_images_of_planes: false            # Plot individual plots of each plane's image (e.g. in the source plane)?
fit_imaging: {}                            # Settings for plots of fits to imaging datasets (e.g. FitImagingPlotter).
tracer:                               # Settings for plots of tracers (e.g. TracerPlotter).
  subplot_tracer: true                # Plot subplot of all quantities in each tracer (e.g. images, convergence)?
  all_at_end_png: true                     # Plot all individual plots listed below as .png (even if False)?
  all_at_end_fits: true                    # Plot all individual plots listed below as .fits (even if False)?
  all_at_end_pdf: false                    # Plot all individual plots listed below as publication-quality .pdf (even if False)?
  subplot_galaxies_images: false              # Plot subplot of the image of each plane in the tracer?
  image: true                              # Plot image of the tracer (e.g. lens and lensed source in the image-plane)?
  source_plane_image: true                 # Plot image of the tracer's source-plane?
  lens_image: true                         # Plot image of the foreground lens galaxy (log10)?
  convergence: true                        # Plot image of the tracer's convergence (log10)?
  potential: false                         # Plot image of the tracer's potential (log10)?
  deflections: false                       # Plot images of the tracer's y and x deflections?
  magnification: false                     # Plot image of the tracer's magnification?
galaxies_1d:                                  # Settings for 1D plots of galaxies (e.g. GalaxiesPlotter).
  image: false
  convergence: false
  potential: false  
inversion:                                 # Settings for plots of inversions (e.g. InversionPlotter).
  subplot_inversion: true                  # Plot subplot of all quantities in each inversion (e.g. reconstrucuted image, reconstruction)?
  subplot_mappings: false                  # Plot subplot of the image-to-source pixels mappings of each pixelization?
  all_at_end_png: true                     # Plot all individual plots listed below as .png (even if False)?
  all_at_end_fits: true                    # Plot all individual plots listed below as .fits (even if False)?
  all_at_end_pdf: false                    # Plot all individual plots listed below as publication-quality .pdf (even if False)?
  data_subtracted: false                   # Plot individual plots of the data with the other inversion linear objects subtracted?
  errors: false                            # Plot image of the errors of every mesh-pixel reconstructed value?
  sub_pixels_per_image_pixels: false       # Plot the number of sub pixels per masked data pixels?
  mesh_pixels_per_image_pixels: false      # Plot the number of image-plane mesh pixels per masked data pixels?
  image_pixels_per_mesh_pixels: false      # Plot the number of image pixels in each pixel of the mesh?
  reconstructed_image: false               # Plot image of the reconstructed data (e.g. in the image-plane)?
  reconstruction: false                    # Plot the reconstructed inversion (e.g. the pixelization's mesh in the source-plane)?
  regularization_weights: false            # Plot the effective regularization weight of every inversion mesh pixel?
adapt:                                     # Settings for plots of adapt images used by adaptive pixelizations.
  images_of_galaxies: true
  model_image: true
interferometer:                            # Settings for plots of interferometer datasets (e.g. InterferometerPlotter).
  amplitudes_vs_uv_distances: false
  phases_vs_uv_distances: false
  uv_wavelengths: false
  dirty_image: false
  dirty_noise_map: false
  dirty_signal_to_noise_map: false
fit_interferometer:                        # Settings for plots of fits to interferometer datasets (e.g. FitInterferometerPlotter).
  subplot_fit_dirty_images: false          # Plot subplot of the dirty-images of all interferometer datasets?
  subplot_fit_real_space: false            # Plot subplot of the real-space images of all interferometer datasets?
  amplitudes_vs_uv_distances: false
  phases_vs_uv_distances: false
  uv_wavelengths: false
  dirty_image: false
  dirty_noise_map: false
  dirty_signal_to_noise_map: false
  dirty_residual_map: false
  dirty_normalized_residual_map: false
  dirty_chi_squared_map: false
fit_ellipse:                               # Settings for plots of ellipse fitting fits (e.g. FitEllipse)
  data : true                              # Plot the data of the ellipse fit?
  data_no_ellipse: true                    # Plot the data without the black data ellipses, which obscure noisy data?
fit_quantity:                              # Settings for plots of fit quantities (e.g. FitQuantityPlotter).
  all_at_end_png: true                     # Plot all individual plots listed below as .png (even if False)?
  all_at_end_fits: true                    # Plot all individual plots listed below as .fits (even if False)?
  all_at_end_pdf: false                    # Plot all individual plots listed below as publication-quality .pdf (even if False)?
  chi_squared_map: false
  subplot_fit: true
  image: true
  model_image: false
  noise_map: false
  residual_map: false
  normalized_residual_map: false
galaxies:                                  # Settings for plots of galaxies (e.g. GalaxiesPlotter).
  subplot_galaxies: true                      # Plot subplot of all quantities in each galaxies group (e.g. images, convergence)?
  all_at_end_png: true                     # Plot all individual plots listed below as .png (even if False)?
  all_at_end_fits: true                    # Plot all individual plots listed below as .fits (even if False)?
  all_at_end_pdf: false                    # Plot all individual plots listed below as publication-quality .pdf (even if False)?
  subplot_galaxy_images: false             # Plot subplot of the image of each galaxy in the model?
  image: false
  source_plane_image: false
  convergence: false
  deflections: false
  potential: false
  magnification: false
