PySwarmsGlobal:
  run:
    iters: 2000
  search:
    cognitive: 0.5
    ftol: -.inf
    inertia: 0.9
    n_particles: 50
    social: 0.3
  initialize:
    method: ball
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  updates:
    iterations_per_update: 5000
    remove_state_files_at_end: true
PySwarmsLocal:
  run:
    iters: 2000
  search:
    cognitive: 0.5
    ftol: -.inf
    inertia: 0.9
    minkowski_p_norm: 2
    n_particles: 50
    number_of_k_neighbors: 3
    social: 0.3
  initialize:
    method: ball
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  updates:
    iterations_per_update: 5000
    remove_state_files_at_end: true
LBFGS:
  search:
    tol: null
  options:
    disp: false
    eps: 1.0e-08
    ftol: 2.220446049250313e-09
    gtol: 1.0e-05
    iprint: -1.0
    maxcor: 10
    maxfun: 15000
    maxiter: 15000
    maxls: 20
  initialize:
    method: ball
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  updates:
    iterations_per_update: 5000
    remove_state_files_at_end: true
Drawer:
  search:
    total_draws: 50
  initialize:
    method: ball
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  updates:
    iterations_per_update: 5000
    remove_state_files_at_end: true
