#!/bin/bash -l

#SBATCH -N 1
#SBATCH -J visibilities_via_preload_no_parallel
#SBATCH -o output/visibilities_via_preload_no_parallel/output.%A.out
#SBATCH -e error/visibilities_via_preload_no_parallel/error.%A.err
#SBATCH -p cosma7
#SBATCH -A dp004
#SBATCH -t 1:00:00   # longest job
#SBATCH --mail-type=END                          # notifications for job done & fail
#SBATCH --mail-user=james.w.nightingale@durham.ac.uk

module purge
module load python/3.6.5
source /cosma/home/dp004/dc-nigh1/PyAutoLens/bin/activate_jam_c7
NUMBA_NUM_THREADS=1

python3 visibilities_via_preload_no_parallel.py